### ISSUE TITLE
plugin is broken on v1.5.3

### ISSUE THREAD

**Issue by CeaselessWatcher** [drPilman/obsidian-graph-nested-tags#6]
plugin cannot be downloaded/updated/enabled on obsidian version 1.5.3
main.js seems to have been renamed to main.ts, which might cause the issue
I tried to manually install the plugin, but it wouldn't let me enable it still

Older versions of the plugin work perfectly

**Comment by ShahriarKh** [comment]
+1
Manually installing v1.0.1 works, but installing/updating v1.0.2 gives an error.

**Comment by dsdy120** [comment]
Plugin does not install from the community plugins menu in v1.5.3 as well for me. Have not yet tried to manually install, but noted the same discrepancy between main.ts filename in the git repo and main.js in the README instructions as indicated by @CeaselessWatcher

**Comment by drPilman** [comment]
I'm sorry for that, I forgot to confirm the release and Obsidian didn't find it on github.

**Comment by drPilman** [comment]
I checked from a new device, it's working now

**Comment by CeaselessWatcher** [comment]
I also checked with my main device, it works fine now, thanks :)
